language:
  ruby

rvm:
  - '2.0'
  - '2.1'
  - '2.2'
  - '2.3.0'
  - '2.4.0'

before_install:
  - gem install bundler

install:
  - gem install bundler
  - gem install rubocop
  - gem install rainbow -v '2.1.0'
  - bundle install

script:
  - bundle exec rubocop


